verf   = ~/casioemu/models/fx991cnxfVirtual
verc   = ~/casioemu/models/models/fx991cnxVirtual
rom2   = ~/casioemu/models/fx991cnxVirtual
lifted = ~/nxu16-decompiler/rom991cnx_lifted.py
emu    = ~/casioemu
multi  = ~/casioemu/models/fx991cnxfVirtual ~/casioemu/models/fx991cnxVirtual ~/casioemu/models/models/fx991cnx ~/casioemu/models/models/fx991cnxVirtual
ropfile = ~/Downloads/Pixel Editor 𝑷𝒓𝒐 - v1.1.rop
