/* 由 tools/crop-chars 生成 —— 机型字库的**单字节**字符表（行=高半字节、列=低半字节）
 * 注意：这台机器**不是 ASCII**！0x68 是 "Abs(" 而不是 'h'。
 * 用法：rprint_at(30, 20, "\x31\xA7\x32");   // 1+2  */
#ifndef CROP_RCHARS_H
#define CROP_RCHARS_H

#define RC_S00        0x00   /*  */
#define RC_S01        0x01   /*  */
#define RC_S02        0x02   /*  */
#define RC_S03        0x03   /*  */
#define RC_S04        0x04   /*  */
#define RC_S05        0x05   /*  */
#define RC_S06        0x06   /*  */
#define RC_S07        0x07   /*  */
#define RC_S08        0x08   /*  */
#define RC_S09        0x09   /*  */
#define RC_S0A        0x0A   /*  */
#define RC_S0B        0x0B   /*  */
#define RC_S0C        0x0C   /*  */
#define RC_S0D        0x0D   /*  */
#define RC_S0E        0x0E   /*  */
#define RC_S0F        0x0F   /*  */
#define RC_S10        0x10   /* 𝒙 */
#define RC_S11        0x11   /* 𝒚 */
#define RC_S12        0x12   /* 𝒛 */
#define RC_S13        0x13   /* … */
#define RC_S14        0x14   /* ▲ */
#define RC_S15        0x15   /* ▼ */
#define RC_S16        0x16   /* ▸ */
#define RC_S17        0x17   /* ₋ */
#define RC_S18        0x18   /* $ */
#define RC_S19        0x19   /* ◁ */
#define RC_S1A        0x1A   /* & */
#define RC_S1B        0x1B   /* 𝑡 */
#define RC_S1C        0x1C   /* ᴛ */
#define RC_S1D        0x1D   /* ₜ */
#define RC_S1E        0x1E   /* ₕ */
#define RC_S1F        0x1F   /* ₅ */
#define RC_S20        0x20   /* 空格 */
#define RC_S21        0x21   /* ! */
#define RC_S22        0x22   /* " */
#define RC_S23        0x23   /* # */
#define RC_S24        0x24   /* × */
#define RC_S25        0x25   /* % */
#define RC_S26        0x26   /* ÷ */
#define RC_S27        0x27   /* ' */
#define RC_S28        0x28   /* ( */
#define RC_S29        0x29   /* ) */
#define RC_S2A        0x2A   /* ⋅ */
#define RC_S2B        0x2B   /* + */
#define RC_S2C        0x2C   /* , */
#define RC_S2D        0x2D   /* - */
#define RC_S2E        0x2E   /* . */
#define RC_S2F        0x2F   /* / */
#define RC_N0         0x30   /* 0 */
#define RC_N1         0x31   /* 1 */
#define RC_N2         0x32   /* 2 */
#define RC_N3         0x33   /* 3 */
#define RC_N4         0x34   /* 4 */
#define RC_N5         0x35   /* 5 */
#define RC_N6         0x36   /* 6 */
#define RC_N7         0x37   /* 7 */
#define RC_N8         0x38   /* 8 */
#define RC_N9         0x39   /* 9 */
#define RC_S3A        0x3A   /* : */
#define RC_S3B        0x3B   /* ; */
#define RC_S3C        0x3C   /* < */
#define RC_S3D        0x3D   /* = */
#define RC_S3E        0x3E   /* > */
#define RC_S3F        0x3F   /* ? */
#define RC_A          0x41   /* A */
#define RC_B          0x42   /* B */
#define RC_C          0x43   /* C */
#define RC_D          0x44   /* D */
#define RC_E          0x45   /* E */
#define RC_F          0x46   /* F */
#define RC_G          0x47   /* G */
#define RC_H          0x48   /* H */
#define RC_I          0x49   /* I */
#define RC_J          0x4A   /* J */
#define RC_K          0x4B   /* K */
#define RC_L          0x4C   /* L */
#define RC_M          0x4D   /* M */
#define RC_N          0x4E   /* N */
#define RC_O          0x4F   /* O */
#define RC_P          0x50   /* P */
#define RC_Q          0x51   /* Q */
#define RC_R          0x52   /* R */
#define RC_S          0x53   /* S */
#define RC_T          0x54   /* T */
#define RC_U          0x55   /* U */
#define RC_V          0x56   /* V */
#define RC_W          0x57   /* W */
#define RC_X          0x58   /* X */
#define RC_Y          0x59   /* Y */
#define RC_Z          0x5A   /* Z */
#define RC_S5B        0x5B   /* [ */
#define RC_S5C        0x5C   /* ▫ */
#define RC_S5D        0x5D   /* ] */
#define RC_S5E        0x5E   /* ^ */
#define RC_S5F        0x5F   /* _ */
#define RC_S60        0x60   /* − */
#define RC_A_61       0x61   /* a */
#define RC_B_62       0x62   /* b */
#define RC_C_63       0x63   /* c */
#define RC_D_64       0x64   /* d */
#define RC_E_65       0x65   /* e */
#define RC_F_66       0x66   /* f */
#define RC_G_67       0x67   /* g */
#define RC_H_68       0x68   /* h */
#define RC_I_69       0x69   /* i */
#define RC_J_6A       0x6A   /* j */
#define RC_K_6B       0x6B   /* k */
#define RC_L_6C       0x6C   /* l */
#define RC_M_6D       0x6D   /* m */
#define RC_N_6E       0x6E   /* n */
#define RC_O_6F       0x6F   /* o */
#define RC_P_70       0x70   /* p */
#define RC_Q_71       0x71   /* q */
#define RC_R_72       0x72   /* r */
#define RC_S_73       0x73   /* s */
#define RC_T_74       0x74   /* t */
#define RC_U_75       0x75   /* u */
#define RC_V_76       0x76   /* v */
#define RC_W_77       0x77   /* w */
#define RC_X_78       0x78   /* x */
#define RC_Y_79       0x79   /* y */
#define RC_Z_7A       0x7A   /* z */
#define RC_S7B        0x7B   /* { */
#define RC_S7C        0x7C   /* | */
#define RC_S7D        0x7D   /* } */
#define RC_S7E        0x7E   /* ~ */
#define RC_S7F        0x7F   /* ├ */
#define RC_S80        0x80   /* 𝒊 */
#define RC_S81        0x81   /* 𝒆 */
#define RC_S82        0x82   /*  */
#define RC_S83        0x83   /*  */
#define RC_S84        0x84   /*  */
#define RC_S85        0x85   /* ° */
#define RC_S86        0x86   /* ʳ */
#define RC_S87        0x87   /* ᵍ */
#define RC_S88        0x88   /* ∠ */
#define RC_S89        0x89   /*  */
#define RC_S8A        0x8A   /*  */
#define RC_S8B        0x8B   /*  */
#define RC_S8C        0x8C   /*  */
#define RC_S8D        0x8D   /* → */
#define RC_S8E        0x8E   /* ∏ */
#define RC_S8F        0x8F   /* ⇒ */
#define RC_S90        0x90   /*  */
#define RC_S91        0x91   /*  */
#define RC_S92        0x92   /*  */
#define RC_S93        0x93   /* ⌟ */
#define RC_S94        0x94   /* ≤ */
#define RC_S95        0x95   /* ≠ */
#define RC_S96        0x96   /* ≥ */
#define RC_S97        0x97   /*  */
#define RC_S98        0x98   /* √ */
#define RC_S99        0x99   /* ∫ */
#define RC_S9A        0x9A   /* ᴀ */
#define RC_S9B        0x9B   /* ʙ */
#define RC_S9C        0x9C   /* ᴄ */
#define RC_S9D        0x9D   /* ₙ */
#define RC_S9E        0x9E   /* ▶ */
#define RC_S9F        0x9F   /* ◀ */
#define RC_SA0        0xA0   /* ⁰ */
#define RC_SA1        0xA1   /* ¹ */
#define RC_SA2        0xA2   /* ² */
#define RC_SA3        0xA3   /* ³ */
#define RC_SA4        0xA4   /* ⁴ */
#define RC_SA5        0xA5   /* ⁵ */
#define RC_SA6        0xA6   /* ⁶ */
#define RC_SA7        0xA7   /* ⁷ */
#define RC_SA8        0xA8   /* ⁸ */
#define RC_SA9        0xA9   /* ⁹ */
#define RC_SAA        0xAA   /*  */
#define RC_SAB        0xAB   /*  */
#define RC_SAC        0xAC   /*  */
#define RC_SAD        0xAD   /* ₍ */
#define RC_SAE        0xAE   /* ₎ */
#define RC_SAF        0xAF   /*  */
#define RC_SB0        0xB0   /* ₀ */
#define RC_SB1        0xB1   /* ₁ */
#define RC_SB2        0xB2   /* ₂ */
#define RC_SB3        0xB3   /*  */
#define RC_SB4        0xB4   /* ꜰ */
#define RC_SB5        0xB5   /* ɴ */
#define RC_SB6        0xB6   /* ᴘ */
#define RC_SB7        0xB7   /*  */
#define RC_SB8        0xB8   /* 𝗔 */
#define RC_SB9        0xB9   /* 𝗕 */
#define RC_SBA        0xBA   /* 𝗖 */
#define RC_SBB        0xBB   /* 𝗗 */
#define RC_SBC        0xBC   /* 𝗘 */
#define RC_SBD        0xBD   /* 𝗙 */
#define RC_SBE        0xBE   /* 𝗣 */
#define RC_SBF        0xBF   /* ▷ */
#define RC_SC0        0xC0   /* ∑ */
#define RC_SC1        0xC1   /* 𝛼 */
#define RC_SC2        0xC2   /* 𝛾 */
#define RC_SC3        0xC3   /* 𝜀 */
#define RC_SC4        0xC4   /* 𝜃 */
#define RC_SC5        0xC5   /* 𝜆 */
#define RC_SC6        0xC6   /* 𝜇 */
#define RC_SC7        0xC7   /* 𝜋 */
#define RC_SC8        0xC8   /* 𝜎 */
#define RC_SC9        0xC9   /* 𝜙 */
#define RC_SCA        0xCA   /* ℓ */
#define RC_SCB        0xCB   /* ℏ */
#define RC_SCC        0xCC   /* ▮ */
#define RC_SCD        0xCD   /* ▯ */
#define RC_SCE        0xCE   /* ₃ */
#define RC_SCF        0xCF   /* ＿ */
#define RC_SD0        0xD0   /* 𝐟 */
#define RC_SD1        0xD1   /* 𝐩 */
#define RC_SD2        0xD2   /* 𝐧 */
#define RC_SD3        0xD3   /* 𝝁 */
#define RC_SD4        0xD4   /* 𝐦 */
#define RC_SD5        0xD5   /* 𝐤 */
#define RC_SD6        0xD6   /* 𝐌 */
#define RC_SD7        0xD7   /* 𝐆 */
#define RC_SD8        0xD8   /* 𝐓 */
#define RC_SD9        0xD9   /* 𝐏 */
#define RC_SDA        0xDA   /* 𝐄 */
#define RC_SDB        0xDB   /* 𝐹 */
#define RC_SDC        0xDC   /* ₚ */
#define RC_SDD        0xDD   /* ₑ */
#define RC_SDE        0xDE   /* ᴊ */
#define RC_SDF        0xDF   /* ᴋ */
#define RC_SE0        0xE0   /*  */
#define RC_SE1        0xE1   /*  */
#define RC_SE2        0xE2   /* ₉ */
#define RC_SE3        0xE3   /* Å */
#define RC_SE4        0xE4   /* ₘ */
#define RC_SE5        0xE5   /* ɪ */
#define RC_SE6        0xE6   /* ₄ */
#define RC_SE7        0xE7   /*  */
#define RC_SE8        0xE8   /*  */
#define RC_SE9        0xE9   /*  */
#define RC_SEA        0xEA   /*  */
#define RC_SEB        0xEB   /*  */
#define RC_SEC        0xEC   /*  */
#define RC_SED        0xED   /*  */
#define RC_SEE        0xEE   /*  */
#define RC_SEF        0xEF   /*  */
#define RC_SF0        0xF0   /*  */
#define RC_SF1        0xF1   /*  */
#define RC_SF2        0xF2   /*  */
#define RC_SF3        0xF3   /*  */
#define RC_SF4        0xF4   /*  */
#define RC_SF5        0xF5   /*  */
#define RC_SF6        0xF6   /*  */
#define RC_SF7        0xF7   /*  */
#define RC_SF8        0xF8   /*  */
#define RC_SF9        0xF9   /*  */
#define RC_SFA        0xFA   /*  */
#define RC_SFB        0xFB   /*  */
#define RC_SFC        0xFC   /*  */
#define RC_SFD        0xFD   /*  */
#define RC_SFE        0xFE   /*  */
#define RC_SFF        0xFF   /*  */

#endif /* CROP_RCHARS_H */
