/* 由 tools/crop-chars 生成 —— 机型字库的**单字节**字符表（行=高半字节、列=低半字节）
 * 注意：这台机器**不是 ASCII**！0x68 是 "Abs(" 而不是 'h'。
 * 用法：rprint_at(30, 20, "\x31\xA7\x32");   // 1+2  */
#ifndef CROP_RCHARS_H
#define CROP_RCHARS_H

#define RC_S01        0x01   /* 空格 */
#define RC_S19        0x19   /* ▯ */
#define RC_S20        0x20   /* 𝒊 */
#define RC_S21        0x21   /* 𝒆 */
#define RC_S22        0x22   /* 𝜋 */
#define RC_S23        0x23   /* : */
#define RC_S24        0x24   /* $ */
#define RC_S25        0x25   /* ? */
#define RC_S2C        0x2C   /* , */
#define RC_S2D        0x2D   /*  */
#define RC_S2E        0x2E   /* . */
#define RC_N0         0x30   /* 0 */
#define RC_N1         0x31   /* 1 */
#define RC_N2         0x32   /* 2 */
#define RC_N3         0x33   /* 3 */
#define RC_N4         0x34   /* 4 */
#define RC_N5         0x35   /* 5 */
#define RC_N6         0x36   /* 6 */
#define RC_N7         0x37   /* 7 */
#define RC_N8         0x38   /* 8 */
#define RC_N9         0x39   /* 9 */
#define RC_S3A        0x3A   /* 𝗔 */
#define RC_S3B        0x3B   /* 𝗕 */
#define RC_S3C        0x3C   /* 𝗖 */
#define RC_S3D        0x3D   /* 𝗗 */
#define RC_S3E        0x3E   /* 𝗘 */
#define RC_S3F        0x3F   /* 𝗙 */
#define RC_M          0x40   /* M */
#define RC_ANS        0x41   /* Ans */
#define RC_A          0x42   /* A */
#define RC_B          0x43   /* B */
#define RC_C          0x44   /* C */
#define RC_D          0x45   /* D */
#define RC_E          0x46   /* E */
#define RC_F          0x47   /* F */
#define RC_S48        0x48   /* 𝒙 */
#define RC_S49        0x49   /* 𝒚 */
#define RC_PREANS     0x4A   /* PreAns */
#define RC_S50        0x50   /* ∑( */
#define RC_S51        0x51   /* ∫( */
#define RC_DD         0x52   /* d/d𝒙( */
#define RC_S53        0x53   /* ∏( */
#define RC_MIN        0x58   /* Min( */
#define RC_MAX        0x59   /* Max( */
#define RC_MEAN       0x5A   /* Mean( */
#define RC_SUM        0x5B   /* Sum( */
#define RC_S60        0x60   /* ( */
#define RC_P          0x61   /* P( */
#define RC_Q          0x62   /* Q( */
#define RC_R          0x63   /* R( */
#define RC_NOT        0x64   /* Not( */
#define RC_NEG        0x65   /* Neg( */
#define RC_CONJG      0x66   /* Conjg( */
#define RC_ARG        0x67   /* Arg( */
#define RC_ABS        0x68   /* Abs( */
#define RC_RND        0x69   /* Rnd( */
#define RC_DET        0x6A   /* Det( */
#define RC_TRN        0x6B   /* Trn( */
#define RC_SINH       0x6C   /* sinh( */
#define RC_COSH       0x6D   /* cosh( */
#define RC_TANH       0x6E   /* tanh( */
#define RC_SINH_6F    0x6F   /* sinh( */
#define RC_COSH_70    0x70   /* cosh( */
#define RC_TANH_71    0x71   /* tanh( */
#define RC_S72        0x72   /* 𝒆^( */
#define RC_S73        0x73   /* ^( */
#define RC_S74        0x74   /* √( */
#define RC_LN         0x75   /* ln( */
#define RC_S76        0x76   /* ³√( */
#define RC_SIN        0x77   /* sin( */
#define RC_COS        0x78   /* cos( */
#define RC_TAN        0x79   /* tan( */
#define RC_SIN_7A     0x7A   /* sin( */
#define RC_COS_7B     0x7B   /* cos( */
#define RC_TAN_7C     0x7C   /* tan( */
#define RC_LOG        0x7D   /* log( */
#define RC_POL        0x7E   /* Pol( */
#define RC_REC        0x7F   /* Rec( */
#define RC_INT        0x83   /* Int( */
#define RC_INTG       0x84   /* Intg( */
#define RC_REF        0x85   /* Ref( */
#define RC_RREF       0x86   /* Rref( */
#define RC_RANINT     0x87   /* RanInt#( */
#define RC_GCD        0x88   /* GCD( */
#define RC_LCM        0x89   /* LCM( */
#define RC_RNDFIX     0x8A   /* RndFix( */
#define RC_REP        0x8F   /* ReP( */
#define RC_IMP        0x90   /* ImP( */
#define RC_IDENTITY   0x91   /* Identity( */
#define RC_UNITV      0x92   /* UnitV( */
#define RC_ANGLE      0x93   /* Angle( */
#define RC_OR         0xA0   /* or */
#define RC_XOR        0xA1   /* xor */
#define RC_XNOR       0xA2   /* xnor */
#define RC_AND        0xA3   /* and */
#define RC_SA5        0xA5   /* = */
#define RC_SA6        0xA6   /* + */
#define RC_SA7        0xA7   /* - */
#define RC_SA8        0xA8   /* × */
#define RC_SA9        0xA9   /* ÷ */
#define RC_R_AA       0xAA   /* ÷R */
#define RC_SAB        0xAB   /* ⋅ */
#define RC_SAC        0xAC   /* ∠ */
#define RC_SAD        0xAD   /* 𝗣 */
#define RC_SAE        0xAE   /* 𝗖 */
#define RC_SB8        0xB8   /*  */
#define RC_SB9        0xB9   /*  */
#define RC_SBA        0xBA   /* ₁ */
#define RC_SBB        0xBB   /* ₂ */
#define RC_SC0        0xC0   /* − */
#define RC_B_C1       0xC1   /* b */
#define RC_O          0xC2   /* o */
#define RC_D_C3       0xC3   /* d */
#define RC_H          0xC4   /* h */
#define RC_SC8        0xC8   /* ⌟ */
#define RC_SC9        0xC9   /* ^( */
#define RC_SCA        0xCA   /* √( */
#define RC_SD0        0xD0   /* ) */
#define RC_T          0xD1   /* ▸t */
#define RC_AB         0xD2   /* ▸a+b𝒊 */
#define RC_R_D3       0xD3   /* ▸r∠𝜃 */
#define RC_SD4        0xD4   /*  */
#define RC_SD5        0xD5   /* ² */
#define RC_SD6        0xD6   /* ³ */
#define RC_SD7        0xD7   /* % */
#define RC_SD8        0xD8   /* ! */
#define RC_SD9        0xD9   /* ° */
#define RC_SDA        0xDA   /* ʳ */
#define RC_SDB        0xDB   /* ᵍ */
#define RC_SDC        0xDC   /* ▫ */
#define RC_SDD        0xDD   /* 𝐄 */
#define RC_SDE        0xDE   /* 𝐏 */
#define RC_SDF        0xDF   /* 𝐓 */
#define RC_SE0        0xE0   /* 𝐆 */
#define RC_SE1        0xE1   /* 𝐌 */
#define RC_SE2        0xE2   /* 𝐤 */
#define RC_SE3        0xE3   /* 𝐦 */
#define RC_SE4        0xE4   /* 𝝁 */
#define RC_SE5        0xE5   /* 𝐧 */
#define RC_SE6        0xE6   /* 𝐩 */
#define RC_SE7        0xE7   /* 𝐟 */
#define RC_SIMP       0xE9   /* ▸Simp  */

#endif /* CROP_RCHARS_H */
